spring:
  application:
    name: kafka-06-base
  kafka:
    bootstrap-servers: localhost:9091,localhost:9092,localhost:9093 # kafka集群地址
    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: earliest
